apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculationservice
  namespace: easytrade-nonprod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculationservice
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: calculationservice
        app.kubernetes.io/version: ce61dca
        app.kubernetes.io/part-of: easytrade
        dynatrace-release-stage: non-prod
    spec:
      containers:
      - name: calculationservice
        image: gcr.io/dynatrace-demoability/easytrade/calculationservice:ce61dca
        env:
        - name: DT_RELEASE_PRODUCT
          value: easytrade
        - name: DT_RELEASE_STAGE
          value: nonprod
        - name: DT_RELEASE_BUILD_VERSION
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app.kubernetes.io/version']
        - name: DT_RELEASE_VERSION
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app.kubernetes.io/version']
        resources:
          requests:
            cpu: 100m
            memory: 10Mi
          limits:
            cpu: 1000m
            memory: 50Mi
