apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: easytrade-nonprod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: db
        app.kubernetes.io/version: ce61dca
        app.kubernetes.io/part-of: easytrade
        dynatrace-release-stage: non-prod
    spec:
      containers:
      - name: db
        image: gcr.io/dynatrace-demoability/easytrade/db:ce61dca
        ports:
        - containerPort: 1433
        env:
        - name: DT_RELEASE_PRODUCT
          value: easytrade
        - name: DT_RELEASE_STAGE
          value: nonprod
        - name: DT_RELEASE_BUILD_VERSION
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app.kubernetes.io/version']
        - name: DT_RELEASE_VERSION
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app.kubernetes.io/version']
        - name: SA_PASSWORD
          value: "yourStrong(!)Password"
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1536Mi
---
apiVersion: v1
kind: Service
metadata:
  name: easytrade-nonprod-db
  namespace: easytrade-nonprod
spec:
  type: ClusterIP
  selector:
    app: db
  ports:
  - name: mssql
    port: 1433
    targetPort: 1433
