apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-reverseproxy
  namespace: easytrade-nonprod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-reverseproxy
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: frontend-reverseproxy
        app.kubernetes.io/version: ce61dca
        app.kubernetes.io/part-of: easytrade
        dynatrace-release-stage: non-prod
    spec:
      containers:
      - name: frontend-reverseproxy
        image: gcr.io/dynatrace-demoability/easytrade/frontendreverseproxy:ce61dca
        ports:
        - containerPort: 80
        env:
        - name: DT_RELEASE_PRODUCT
          value: easytrade
        - name: DT_RELEASE_STAGE
          value: nonprod
        - name: DT_RELEASE_BUILD_VERSION
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app.kubernetes.io/version']
        - name: DT_RELEASE_VERSION
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app.kubernetes.io/version']
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 1000m
            memory: 75Mi
---
apiVersion: v1
kind: Service
metadata:
  name: easytrade-nonprod-frontend-reverseproxy
  namespace: easytrade-nonprod
spec:
  type: LoadBalancer
  selector:
    app: frontend-reverseproxy
  ports:
    - name: http
      port: 80
      targetPort: 80
