---
apiVersion: v1
kind: Namespace
metadata:
  name: easytrade-nonprod
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: easytrade-nonprod
  namespace: easytrade-nonprod
spec:
  hard:
    requests.cpu: 4000m
    requests.memory: 6Gi
    pods: 100
