apiVersion: apps/v1
kind: Deployment
metadata:
  name: offerservice
  namespace: easytrade-nonprod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: offerservice
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: offerservice
        app.kubernetes.io/version: ce61dca
        app.kubernetes.io/part-of: easytrade
        dynatrace-release-stage: non-prod
    spec:
      containers:
      - name: offerservice
        image: gcr.io/dynatrace-demoability/easytrade/offerservice:ce61dca
        ports:
        - containerPort: 8080
        env:
        - name: DT_RELEASE_PRODUCT
          value: easytrade
        - name: DT_RELEASE_STAGE
          value: nonprod
        - name: DT_RELEASE_BUILD_VERSION
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app.kubernetes.io/version']
        - name: DT_RELEASE_VERSION
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app.kubernetes.io/version']
        - name: LOGIN_SERVICE_PORT
          value: '80'
        - name: LOGIN_SERVICE_BASE_URL
          value: loginservice
        - name: MANAGER_BASE_URL
          value: manager
        - name: MANAGER_PORT
          value: '80'
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 1000m
            memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: offerservice
  namespace: easytrade-nonprod
spec:
  type: ClusterIP
  selector:
    app: offerservice
  ports:
  - name: http
    port: 8080
    targetPort: 8080
