apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: easytrade-nonprod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rabbitmq
        app.kubernetes.io/version: ce61dca
        app.kubernetes.io/part-of: easytrade
        dynatrace-release-stage: non-prod
    spec:
      containers:
      - name: rabbitmq
        image: gcr.io/dynatrace-demoability/easytrade/rabbitmq:ce61dca
        ports:
        - containerPort: 5672
        - containerPort: 15672
        env:
        - name: DT_RELEASE_PRODUCT
          value: easytrade
        - name: DT_RELEASE_STAGE
          value: nonprod
        - name: DT_RELEASE_BUILD_VERSION
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app.kubernetes.io/version']
        - name: DT_RELEASE_VERSION
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app.kubernetes.io/version']
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 1000m
            memory: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: easytrade-nonprod
spec:
  type: ClusterIP
  selector:
    app: rabbitmq
  ports:
  - name: rabbitmq-listener
    port: 5672
    targetPort: 5672
  - name: rabbitmq-ui
    port: 15672
    targetPort: 15672
